version: '2.4'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://transcription_db:3306/bootdb?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  MAX_FILE_SIZE: 15MB
  MAX_REQUEST_SIZE: 15MB
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: 5672
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  RABBITMQ_QUEUE_EXTRACT: audio-extract
  RABBITMQ_QUEUE_SUBTITLE: subtitle-receive
  RABBITMQ_EXCHANGE: amp.direct
  TRANSLATOR_URL: https://translation.googleapis.com
  TRANSLATOR_API_KEY: AIzaSyCYX9soUSBUk55LBfqXpIycVWPEczgjTNk
  
services:
  transcription_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports: 
      - "3306:3306"
    volumes:
      - transcription_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management-alpine    
    ports:
      - 5672:5672
      - 15672:15672

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  transcription-api-inatel:
    image: emoura/transcription-api:0.0.1-SNAPSHOT
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - "8081:8081"
    environment:
      <<: *database-variables
    depends_on:
      - rabbitmq
      - transcription_db

volumes:
  transcription_data:
  rabbitmq-data: