server:
    port: ${SPRING_PORT:8081}
    error:
        include-stacktrace: never

spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/subtitledb?&createDatabaseIfNotExist=true}
        username: ${SPRING_DATASOURCE_USERNAME:root}
        password: ${SPRING_DATASOURCE_PASSWORD:root}
    jpa:
        hibernate:
            ddl-auto: update   

    servlet:
        multipart:
            max-file-size:  ${MAX_FILE_SIZE:15MB}
            max-request-size:  ${MAX_REQUEST_SIZE:15MB}
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USERNAME:guest}
        password: ${RABBITMQ_PASSWORD:guest}
    # cache:
    #     type: redis
    # redis:
    #     host: localhost
    #     port: 6379

google_translate:
    base_url: ${TRANSLATOR_URL:https://translation.googleapis.com}
    api_key: ${TRANSLATOR_API_KEY:AIzaSyCYX9soUSBUk55LBfqXpIycVWPEczgjTNk}

queue:
    extract: ${RABBITMQ_QUEUE_EXTRACT:audio-extract}
    subtitle: ${RABBITMQ_QUEUE_SUBTITLE:subtitle-receive}
    exchange: ${RABBITMQ_EXCHANGE:amp.direct}

# api:
#     key: ${API_KEY:123abc}



logging:
    level:
        root: INFO
        org:
            springframework:
                web: INFO
